In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn import svm as s
import numpy as np
import os
import cv2

import scipy.ndimage

from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt

In [2]:
def mlp(data, labels):

    # Split data into test and train data
    x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.33, random_state=42)

    # Multi layer perceptron class instance
    clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=3000, random_state=1, max_iter=200000)

    # Training
    clf.fit(x_train, y_train)

    # Testing
    y_pred = clf.predict(x_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy
    accuracy = clf.score(x_test, y_test)

    print("\n-- Multi Layer Perceptron --")
    print("Training completed")
    print("Accuracy : " + str(accuracy))
    print("Confusion Matrix :")
    print(cm)

In [3]:
def knn(data, labels):

    # Split data into test and train data
    x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.33, random_state=42)

    # KNN class instance
    clf = KNeighborsClassifier(n_neighbors=3)

    # Training
    clf.fit(x_train, y_train)

    # Testing
    y_pred = clf.predict(x_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy
    accuracy = clf.score(x_test, y_test)

    print("\n-- K Nearest Neighbors --")
    print("Training completed")
    print("Accuracy : " + str(accuracy))
    print("Confusion Matrix :")
    print(cm)


In [4]:
def svm(data, labels):

    # Split data into test and train data
    x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.33, random_state=42)

    # SVM class instance
    clf = s.SVC(kernel='linear', C=1, gamma=1)

    # Training
    clf.fit(x_train, y_train)

    # Testing
    y_pred = clf.predict(x_test)

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Accuracy
    accuracy = clf.score(x_test, y_test)

    print("\n-- SVM --")
    print("Training completed")
    print("Test Accuracy : " + str(accuracy))
    print("Confusion Matrix :")
    print(cm)
    return clf


In [5]:
def load_dataset(input_path):
    """
    This method load images and their labels from a folder, each folder name is label for all images that contain
    the folder
    :param input_path: Folder path where all data exist
    :return: two list contains images and their labels
    """

    # List that will contain images
    features_list = []

    # List that will contain labels
    features_label = []

    # Load all directory
    for root, dirs, files in os.walk(input_path):

        # Filter through every folder
        for dir in dirs:

            # Filter all files in the folder
            for filename in os.listdir(input_path + "/" + dir):

                # Load image
                training_digit_image = cv2.imread(input_path + "/" + dir + "/" + filename)

                # BGR to Gray
                gray = cv2.cvtColor(training_digit_image, cv2.COLOR_BGR2GRAY)

                # convert to one dim vector
                df = np.array(gray).ravel()

                # Append image and it's label to training list
                features_list.append(df)
                features_label.append(dir)

    return features_list, features_label

In [6]:
# Load Data
data, labels = load_dataset("/content/drive/My Drive/digits recognition")

In [7]:
clf=svm(data, labels)
mlp(data, labels)
knn(data, labels)


-- SVM --
Training completed
Test Accuracy : 0.9612403100775194
Confusion Matrix :
[[11  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  1  0 12  2  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0  1  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  1  9  0]
 [ 0  0  0  0  0  0  0  0  0  0 12]]

-- Multi Layer Perceptron --
Training completed
Accuracy : 0.9302325581395349
Confusion Matrix :
[[11  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0]
 [ 0  1  0  0 11  0  0  0  1  0  0]
 [ 0  0  0  0  0 13  0  0  0  2  0]
 [ 0  0  0  0  0  1  9  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  1  0  0  0  0  7  2  0]
 [ 1  0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0  0 12]]

-- K Nearest Neighbors 

In [8]:
def square(img):
    """
    This function resize non square image to square one (height == width)
    :param img: input image as numpy array
    :return: numpy array
    """

    # image after making height equal to width
    squared_image = img

    # Get image height and width
    h = img.shape[0]
    w = img.shape[1]

    # In case height superior than width
    if h > w:
        diff = h-w
        if diff % 2 == 0:
            x1 = np.zeros(shape=(h, diff//2))
            x2 = x1
        else:
            x1 = np.zeros(shape=(h, diff//2))
            x2 = np.zeros(shape=(h, (diff//2)+1))

        squared_image = np.concatenate((x1, img, x2), axis=1)

    # In case height inferior than width
    if h < w:
        diff = w-h
        if diff % 2 == 0:
            x1 = np.zeros(shape=(diff//2, w))
            x2 = x1
        else:
            x1 = np.zeros(shape=(diff//2, w))
            x2 = np.zeros(shape=((diff//2)+1, w))

        squared_image = np.concatenate((x1, img, x2), axis=0)

    return squared_image

In [11]:
# the variable "caracter_list_image" is the output of the segmentation phase
digits=caracter_list_image
# List of predicted classes
prediction = []

for i in range(len(digits)):

    # Get digit
    digit = digits[i]

    # Make the image squared
    squared_digit = square(digit)

    # Resize the image
    resized_digit = cv2.resize(squared_digit, (20, 20), interpolation=cv2.INTER_AREA)

    # Convert to one dim vector
    one_vector_digit = np.array(resized_digit).ravel()

    # Predict digit class
    resultat = clf.predict([one_vector_digit])

    # Append to total predictions
    prediction.append(resultat[0])

print(prediction)

['1', '3', '8', 'tunisie', '3', '1', '6', '5']
